-- Messages from the contact form on the portfolio.
-- Run once: Supabase -> SQL Editor -> New query -> paste -> Run.
-- Safe to run again; it only adds what is missing.
--
-- Anyone can send a message (insert only). Only the signed-in admin can read, mark or delete them,
-- as long as "Allow new users to sign up" is turned OFF (see SETUP.md, step 2).

create table if not exists public.contact_messages (
  id          bigint generated by default as identity primary key,
  name        text not null check (char_length(name) between 1 and 120),
  email       text not null check (char_length(email) between 5 and 200 and email like '%@%'),
  message     text not null check (char_length(message) between 5 and 4000),
  is_read     boolean not null default false,
  created_at  timestamptz not null default now()
);

create index if not exists contact_messages_created_idx on public.contact_messages (created_at desc);

alter table public.contact_messages enable row level security;

drop policy if exists "anyone can send a message" on public.contact_messages;
create policy "anyone can send a message" on public.contact_messages
  for insert to anon, authenticated
  with check (is_read = false);

drop policy if exists "admin can read messages" on public.contact_messages;
create policy "admin can read messages" on public.contact_messages
  for select to authenticated using (true);

drop policy if exists "admin can update messages" on public.contact_messages;
create policy "admin can update messages" on public.contact_messages
  for update to authenticated using (true) with check (true);

drop policy if exists "admin can delete messages" on public.contact_messages;
create policy "admin can delete messages" on public.contact_messages
  for delete to authenticated using (true);
