-- Visitor analytics for the portfolio.
-- Run once: Supabase -> SQL Editor -> New query -> paste -> Run.
-- Safe to run again; it only adds what is missing.
--
-- Note: "admin can view" lets any signed-in user read visits. That is only you
-- as long as "Allow new users to sign up" is turned OFF (see SETUP.md, step 2).

create table if not exists public.site_activities (
  id          bigint generated by default as identity primary key,
  visitor_id  text,
  session_id  text,
  event_type  text not null,
  detail      text,
  page        text,
  device      text,
  browser     text,
  os          text,
  screen      text,
  referrer    text,
  timezone    text,
  language    text,
  created_at  timestamptz not null default now()
);

-- If you created the table from an older version of SETUP.md, add the new columns.
alter table public.site_activities add column if not exists session_id text;
alter table public.site_activities add column if not exists language text;

create index if not exists site_activities_created_idx on public.site_activities (created_at desc);
create index if not exists site_activities_visitor_idx on public.site_activities (visitor_id);

alter table public.site_activities enable row level security;

drop policy if exists "anyone can insert activities" on public.site_activities;
create policy "anyone can insert activities" on public.site_activities
  for insert to anon, authenticated
  with check (true);

drop policy if exists "admin can view activities" on public.site_activities;
create policy "admin can view activities" on public.site_activities
  for select to authenticated
  using (true);
