-- Version history for the site content.
-- Run once: Supabase -> SQL Editor -> New query -> paste -> Run.
-- Safe to run again; it only adds what is missing.
--
-- Before an editing session changes your content, the previous version is saved automatically
-- (at most one every 5 minutes, the latest 60 are kept). You can also save named restore points
-- from the admin (Settings -> Version history). Only the signed-in admin can see or use them.

create table if not exists public.site_content_history (
  id          bigint generated by default as identity primary key,
  data        jsonb not null,
  kind        text not null default 'auto' check (kind in ('auto', 'manual')),
  label       text,
  created_at  timestamptz not null default now()
);

create index if not exists site_content_history_created_idx on public.site_content_history (created_at desc);

alter table public.site_content_history enable row level security;

drop policy if exists "admin can read history" on public.site_content_history;
create policy "admin can read history" on public.site_content_history
  for select to authenticated using (true);

drop policy if exists "admin can add history" on public.site_content_history;
create policy "admin can add history" on public.site_content_history
  for insert to authenticated with check (true);

drop policy if exists "admin can delete history" on public.site_content_history;
create policy "admin can delete history" on public.site_content_history
  for delete to authenticated using (true);

create or replace function public.site_content_snapshot() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  if old.data is distinct from new.data
     and not exists (select 1 from public.site_content_history
                     where kind = 'auto' and created_at > now() - interval '5 minutes') then
    insert into public.site_content_history (data, kind) values (old.data, 'auto');
    delete from public.site_content_history
      where kind = 'auto'
        and id not in (select id from public.site_content_history where kind = 'auto' order by created_at desc limit 60);
  end if;
  return new;
end;
$$;

drop trigger if exists site_content_snapshot on public.site_content;
create trigger site_content_snapshot
  before update on public.site_content
  for each row execute function public.site_content_snapshot();

-- A first restore point with the content as it is right now.
insert into public.site_content_history (data, kind, label)
select data, 'manual', 'Before version history was turned on'
from public.site_content
where id = 1 and not exists (select 1 from public.site_content_history);
