/* Portfolio content. Edit via /admin. */
(function api(DEFAULTS){
  var KEY='shuvo-portfolio-content-v1', CACHE='shuvo-portfolio-remote-cache', SESS='shuvo-admin-session';
  var cfg=window.PORTFOLIO_CONFIG||{}; var URL_=(cfg.supabaseUrl||'').replace(/\/$/,''), ANON=cfg.supabaseAnonKey||'';
  var remote=!!(URL_&&ANON);
  function clone(o){return JSON.parse(JSON.stringify(o));}
  function merge(o){var d=clone(DEFAULTS);if(o&&typeof o==='object')for(var k in o)d[k]=o[k];return d;}
  function ping(){try{window.dispatchEvent(new Event('portfolio-content'));}catch(e){}}
  function read(k){try{var s=localStorage.getItem(k);return s?JSON.parse(s):null;}catch(e){return null;}}
  function load(){return merge(remote?read(CACHE):read(KEY));}
  function hasDraft(){try{return !remote&&!!localStorage.getItem(KEY);}catch(e){return false;}}
  function h(token){var o={apikey:ANON,'Content-Type':'application/json'};o.Authorization='Bearer '+(token||ANON);return o;}
  function fetchRemote(){
    if(!remote) return Promise.resolve(load());
    return fetch(URL_+'/rest/v1/site_content?id=eq.1&select=data',{headers:h()}).then(function(r){return r.ok?r.json():[];}).then(function(rows){
      var d=rows&&rows[0]&&rows[0].data; if(d){try{localStorage.setItem(CACHE,JSON.stringify(d));}catch(e){} ping();} return merge(d);
    }).catch(function(){return load();});
  }
  function getSession(){try{return JSON.parse(sessionStorage.getItem(SESS)||'null');}catch(e){return null;}}
  function setSession(s){try{s?sessionStorage.setItem(SESS,JSON.stringify(s)):sessionStorage.removeItem(SESS);}catch(e){}}
  function auth(body,grant){
    return fetch(URL_+'/auth/v1/token?grant_type='+grant,{method:'POST',headers:{apikey:ANON,'Content-Type':'application/json'},body:JSON.stringify(body)}).then(function(r){return r.json().then(function(j){
      if(!r.ok||!j.access_token) throw new Error(j.error_description||j.msg||'Sign-in failed');
      var s={token:j.access_token,refresh:j.refresh_token,exp:Date.now()+(j.expires_in||3600)*1000-60000,email:j.user&&j.user.email}; setSession(s); return s;});});
  }
  function signIn(email,password){return auth({email:email,password:password},'password');}
  function token(){var s=getSession(); if(!s) return Promise.reject(new Error('Signed out')); if(Date.now()<s.exp) return Promise.resolve(s.token); return auth({refresh_token:s.refresh},'refresh_token').then(function(n){return n.token;});}
  function signOut(){var s=getSession(); setSession(null); if(remote&&s) fetch(URL_+'/auth/v1/logout',{method:'POST',headers:h(s.token)}).catch(function(){});}
  function save(c){
    if(!remote){localStorage.setItem(KEY,JSON.stringify(c));ping();return Promise.resolve();}
    return token().then(function(t){var hd=h(t);hd.Prefer='resolution=merge-duplicates,return=minimal';
      return fetch(URL_+'/rest/v1/site_content',{method:'POST',headers:hd,body:JSON.stringify({id:1,data:c,updated_at:new Date().toISOString()})});
    }).then(function(r){if(!r.ok) return r.text().then(function(x){throw new Error(x||('Save failed '+r.status));}); try{localStorage.setItem(CACHE,JSON.stringify(c));}catch(e){} ping();});
  }
  function uploadImage(blob,ext){
    if(!remote) return Promise.reject(new Error('local'));
    var path='uploads/'+Date.now()+'-'+Math.random().toString(36).slice(2,8)+'.'+(ext||'jpg');
    return token().then(function(t){return fetch(URL_+'/storage/v1/object/media/'+path,{method:'POST',headers:{apikey:ANON,Authorization:'Bearer '+t,'Content-Type':blob.type,'x-upsert':'true'},body:blob});})
      .then(function(r){if(!r.ok) return r.text().then(function(x){throw new Error(x||'Upload failed');}); return URL_+'/storage/v1/object/public/media/'+path;});
  }
  function uploadFile(file,ext){
    if(!remote) return Promise.reject(new Error('local'));
    var extension = ext || (file.name ? file.name.split('.').pop() : 'pdf');
    var path = 'uploads/' + Date.now() + '-' + Math.random().toString(36).slice(2,8) + '.' + extension;
    return token().then(function(t){
      return fetch(URL_ + '/storage/v1/object/media/' + path, {
        method: 'POST',
        headers: {
          apikey: ANON,
          Authorization: 'Bearer ' + t,
          'Content-Type': file.type || 'application/octet-stream',
          'x-upsert': 'true'
        },
        body: file
      });
    }).then(function(r){
      if(!r.ok) return r.text().then(function(x){ throw new Error(x || ('Upload failed ' + r.status)); });
      return URL_ + '/storage/v1/object/public/media/' + path;
    });
  }
  function reset(){try{localStorage.removeItem(KEY);}catch(e){}ping();}
  function buildFile(c){return '/* Portfolio content. Generated by the admin portal on '+new Date().toISOString()+' */\n('+api.toString()+')('+JSON.stringify(c,null,1)+');\n';}
  window.PortfolioContent={KEY:KEY,DEFAULTS:DEFAULTS,remote:remote,config:cfg,load:load,fetchRemote:fetchRemote,save:save,reset:reset,hasDraft:hasDraft,buildFile:buildFile,signIn:signIn,signOut:signOut,getSession:getSession,uploadImage:uploadImage,uploadFile:uploadFile};
})({
 "hobbiesHead": {"label":"05 — Hobbies","title":"Through","italic":"my lens.","intro":"Away from dashboards I take photos. A few I like."},
 "photos": [],
 "certsHead": {"label":"03 — Certifications","title":"Certified in","italic":"what I do."},
 "certifications": [
 {
  "title": "Lean Six Sigma Black Belt",
  "issuer": "",
  "date": "",
  "category": "Lean Six Sigma",
  "credentialId": "",
  "url": "",
  "image": "",
  "note": ""
 },
 {
  "title": "Lean Six Sigma Green Belt",
  "issuer": "",
  "date": "",
  "category": "Lean Six Sigma",
  "credentialId": "",
  "url": "",
  "image": "",
  "note": ""
 },
 {
  "title": "Lean Six Sigma Yellow Belt",
  "issuer": "",
  "date": "",
  "category": "Lean Six Sigma",
  "credentialId": "",
  "url": "",
  "image": "",
  "note": ""
 },
 {
  "title": "MS Excel Skill Assessment",
  "issuer": "LinkedIn",
  "date": "",
  "category": "Excel",
  "credentialId": "",
  "url": "",
  "image": "",
  "note": "Top 5% of 30M people who took this test worldwide."
 },
 {
  "title": "MS Excel Skill Assessment",
  "issuer": "Fiverr",
  "date": "",
  "category": "Excel",
  "credentialId": "",
  "url": "",
  "image": "",
  "note": "Top 10% worldwide, 7.2/10 grade."
 }
],
 "hero": {
  "brand": "Shuvo Ibn Alam",
  "navCta": "Get in touch",
  "intro": "Hi! I'm Shuvo and I leverage robust analytical skills and problem-solving expertise to deliver actionable insights that drive strategic business decisions.",
  "photo": "assets/shuvo.webp",
  "cta1": "View projects",
  "cta2": "Download CV",
  "cvUrl": "",
  "available": "Open to new roles",
  "availableOn": "show"
 },
 "quotes": [
  {
   "a": "Data is useless",
   "b": "without",
   "c": "insight.",
   "by": "— on analytics"
  },
  {
   "a": "In God we trust.",
   "b": "All others bring",
   "c": "data.",
   "by": "— W. Edwards Deming"
  },
  {
   "a": "What gets measured",
   "b": "gets",
   "c": "managed.",
   "by": "— Peter Drucker"
  },
  {
   "a": "Without data you’re",
   "b": "just another",
   "c": "opinion.",
   "by": "— W. Edwards Deming"
  },
  {
   "a": "Turn raw numbers",
   "b": "into",
   "c": "decisions.",
   "by": "— how I work"
  }
 ],
 "stats": [
  {
   "prefix": "",
   "value": 8,
   "suffix": "+",
   "label": "years in ops & data"
  },
  {
   "prefix": "",
   "value": 16,
   "suffix": "",
   "label": "dashboards & tools"
  },
  {
   "prefix": "Top ",
   "value": 5,
   "suffix": "%",
   "label": "LinkedIn Excel test"
  }
 ],
 "marquee": [
  {
   "text": "Power BI"
  },
  {
   "text": "Power Query"
  },
  {
   "text": "Power Pivot"
  },
  {
   "text": "MS Excel"
  },
  {
   "text": "Python"
  },
  {
   "text": "Data modeling"
  },
  {
   "text": "Lean Six Sigma"
  },
  {
   "text": "Web apps"
  }
 ],
 "work": {
  "label": "01 — Projects",
  "title": "Dashboards, tools",
  "italic": "& apps."
 },
 "projects": [
  {
   "id": "oee",
   "title": "OEE Dashboard",
   "cat": "Power BI",
   "summary": "Availability, performance and quality on the shop floor, with loss and rejection drill-downs.",
   "desc": "Focused on shop floor optimization, this dashboard tracks Overall Equipment Effectiveness (OEE) by analyzing its three core components: Availability, Performance, and Quality. It visualizes production losses—such as cavity loss, cycle time loss, and quality defects—to identify root causes of inefficiency. The dashboard also monitors \"Manual vs. Automation\" utilization and tracks rejection rates (e.g., flash, oil/grease issues), empowering the operations team to drive continuous process improvement",
   "tags": [
    "OEE",
    "Loss analysis",
    "Manual vs automation"
   ],
   "image": "",
   "images": [],
   "link": ""
  },
  {
   "id": "sales",
   "title": "Sales Analysis",
   "cat": "Power BI",
   "summary": "Global sales by region and time, with Python trend lines flagging growing vs. dropping buyers.",
   "desc": "This \"Sales Analysis\" dashboard provides a strategic view of global sales performance across different regions and timeframes. It has advanced trend lines created with python to identify \"Growing\" vs. \"Dropping\" buyer volume over multiple years. Key features include dynamic slicers for detailed filtering by Buyer, Customer, and Model, enabling management to pinpoint top-performing clients (e.g., Primark, Decathlon) and assess long-term sales trajectories",
   "tags": [
    "Python visuals",
    "Slicers",
    "Buyer trends"
   ],
   "image": "",
   "images": [],
   "link": ""
  },
  {
   "id": "inv",
   "title": "Inventory & Sales Momentum",
   "cat": "Power BI",
   "summary": "MoM / YoY growth, stock days per buyer and pending-order aging in one hub.",
   "desc": "This dashboard serves as a central hub for monitoring inventory health and sales momentum. It visualizes critical KPIs such as Month-over-Month (MoM) and Year-over-Year (YoY) Sales Growth, alongside a detailed analysis of \"Stock Days\" per buyer to prevent overstocking or stockouts. It also includes a \"Pending Order\" analysis broken down by aging groups, providing actionable insights into order fulfillment bottlenecks and backlog management",
   "tags": [
    "MoM · YoY",
    "Stock days",
    "Aging"
   ],
   "image": "",
   "images": [],
   "link": ""
  },
  {
   "id": "matrix",
   "title": "Sales Matrix Report",
   "cat": "Power BI",
   "summary": "Month × buyer × customer matrix of volume and value, with old vs. new pending orders.",
   "desc": "Designed for granular operational reporting, this dashboard offers a comprehensive matrix view of sales volume and value across all months, buyers, and customers. It allows stakeholders to drill down into specific customer performance (e.g., specific composite mills or fashion houses) and track \"Pending Orders\" categorized by status (Old vs. New). This tool is essential for cross-verifying sales data and managing precise delivery timelines for high-volume accounts",
   "tags": [
    "Matrix",
    "Drill-down",
    "Pending orders"
   ],
   "image": "",
   "images": [],
   "link": ""
  },
  {
   "id": "reject",
   "title": "Rejection Analysis Tool",
   "cat": "Power BI",
   "summary": "Hanger rejection by machine and model, with Pareto and trend analysis of root causes.",
   "desc": "The displayed dashboard titled \"Rejection Analysis Tool\" provides an overview of hanger rejection analysis, showcasing key production metrics such as target vs actual production, rejection rates, and top contributing machines and models. It highlights the main causes of rejection (e.g., Short Mold, Flow Mark, Color Change) and offers insights through trend analysis, Pareto analysis, and machine-specific data to help improve production efficiency and minimize defects.",
   "tags": [
    "Pareto",
    "Root cause",
    "Quality"
   ],
   "image": "",
   "images": [],
   "link": ""
  },
  {
   "id": "prodsum",
   "title": "Production Summary",
   "cat": "Power BI",
   "summary": "Target vs. actual, scrap, WIP and material usage with daily rejection trends.",
   "desc": "This dashboard, titled \"Production Summary Dashboard,\" provides an overview of key production metrics like target vs actual production, scrap, and total output. It breaks down daily production trends, material usage, and rejection rates. Key insights like the breakdown of material types, finished product, WIP, and daily rejection%. It also highlights top machines, tools, and models contributing to production and scrap, while offering a clear visual representation of operational performance in terms of productivity, quality (OEE)",
   "tags": [
    "Target vs actual",
    "WIP",
    "OEE"
   ],
   "image": "",
   "images": [],
   "link": ""
  },
  {
   "id": "manpower",
   "title": "Manpower Mapping",
   "cat": "Power BI",
   "summary": "Workforce distribution across shifts and task categories, from machine operation to packing.",
   "desc": "This dashboard is called \"Manpower Mapping\" which provides an overview of manpower distribution and work categories for date/month, focusing on shifts (morning, evening, night) and various operational tasks such as machine operation, packing, and automation. The visualizations highlight the percentage distribution across different shifts and the breakdown of tasks, offering insights into workforce allocation and productivity for the period. Confidential data has been masked",
   "tags": [
    "Shifts",
    "Workforce",
    "Masked data"
   ],
   "image": "",
   "images": [],
   "link": ""
  },
  {
   "id": "scrap",
   "title": "Production Scrap",
   "cat": "Power BI",
   "summary": "Scrap causes and daily rejection trends by category, machine and model.",
   "desc": "This \"Production Scrap\" dashboard provides a comprehensive overview, covering scrap causes and daily rejection trends. It includes category-wise, machine-wise, and model-wise analysis, allowing for detailed insights into production inefficiencies. Visual elements such as charts and tables offer a clear comparison of scrap performance across units, helping identify areas for improvement in production",
   "tags": [
    "Scrap",
    "Category-wise",
    "Machine-wise"
   ],
   "image": "",
   "images": [],
   "link": ""
  },
  {
   "id": "monitor",
   "title": "Production Monitoring",
   "cat": "Power BI",
   "summary": "Monthly and quarterly targets, WIP, scrap and idle time, with OEE% by quarter.",
   "desc": "This \"Production Monitoring Dashboard\" overviews monthly and quarterly performance, focusing on key metrics like production targets, WIP, scrap rates, and idle time. It includes visual elements such as a funnel chart for monthly progress, a bar chart comparing production to targets, and a pie chart for monthly production distribution. It also features a quarterly breakdown, helping to track overall performance, productivity, quality, and OEE%. It offers a clear view of production trends and areas for improvement.",
   "tags": [
    "Funnel",
    "Quarterly",
    "Idle time"
   ],
   "image": "",
   "images": [],
   "link": ""
  },
  {
   "id": "forecast",
   "title": "Sales Forecast",
   "cat": "Power BI",
   "summary": "Weekly production, sales and forecast deviations across two seasons.",
   "desc": "This \"Sales Forecast Dashboard\" provides a detailed analysis of stock and order status, focusing on weekly production, sales, and forecasts. It includes comparisons between stock levels, outstanding orders, and forecast deviations for two seasons. Visualizations such as line graphs and bar charts track trends in stock status, order fulfillment, and week-over-week forecast changes, helping to monitor supply chain efficiency and demand fulfillment across various models",
   "tags": [
    "Forecast",
    "Week-over-week",
    "Supply chain"
   ],
   "image": "",
   "images": [],
   "link": ""
  },
  {
   "id": "stock",
   "title": "Stock & Order Analysis",
   "cat": "Power BI",
   "summary": "Opening/closing stock, excess stock and YTD orders, with required production by buyer.",
   "desc": "This dashboard provides a comprehensive overview of stock and order analysis for Stock operation. Displays key stock statistics such as opening and closing stock, pending orders, excess stock, and year-to-date (YTD) orders. Segmented by models and buyers, showcasing pending order volumes for prioritizing. Visualizes the required production breakdown, organized by buyer, hanger type, and specific processing steps.",
   "tags": [
    "Stock",
    "YTD",
    "Prioritisation"
   ],
   "image": "",
   "images": [],
   "link": ""
  },
  {
   "id": "model1",
   "title": "Data Modeling · Project 1",
   "cat": "Power BI",
   "summary": "Relational model linking stock history, forecasts, product types and vendors.",
   "desc": "This image showcases a \"Data Model\" created in Power BI, which visually represents the relationships between various tables. Each table contains specific data fields such as stock history, forecast details, product types, and vendor data. The model is built to connect these tables using key relationships, allowing for efficient data analysis and reporting. Power BI's data modeling capabilities, as shown here, help organize and link related datasets, enabling users to create comprehensive reports and insights from multiple data sources. This setup is ideal for managing complex data, such as inventory forecasts, stock analysis, and vendor performance tracking.",
   "tags": [
    "Data model",
    "Relationships",
    "Star schema"
   ],
   "image": "",
   "images": [],
   "link": ""
  },
  {
   "id": "model2",
   "title": "Data Modeling · Project 2",
   "cat": "Power BI",
   "summary": "Second multi-table model for inventory forecasts and vendor performance tracking.",
   "desc": "This image showcases a \"Data Model\" created in Power BI, which visually represents the relationships between various tables. Each table contains specific data fields such as stock history, forecast details, product types, and vendor data. The model is built to connect these tables using key relationships, allowing for efficient data analysis and reporting. This setup is ideal for managing complex data, such as inventory forecasts, stock analysis, and vendor performance tracking.",
   "tags": [
    "Data model",
    "Relationships"
   ],
   "image": "",
   "images": [],
   "link": ""
  },
  {
   "id": "shopfloor",
   "title": "Shop Floor Summary Report",
   "cat": "Excel",
   "summary": "Formula-driven report that calculates production, rejection and material use from raw data.",
   "desc": "I have developed a comprehensive Excel-based Shop Floor Summary Report that provides detailed insights into production, rejection rates, material consumption, and overall performance. The report is powered by complex formulas, enabling automatic calculations and analysis directly from raw data, ensuring accuracy and efficiency in tracking key operational metrics.",
   "tags": [
    "Advanced formulas",
    "Automation"
   ],
   "image": "",
   "images": [],
   "link": ""
  },
  {
   "id": "bday",
   "title": "Birthday & Anniversary Reminder",
   "cat": "Excel",
   "summary": "Pick an employee, draft a greeting and send the email straight from the workbook.",
   "desc": "This Excel project is a tool for managing employee birthday and anniversary reminders. It displays a list of employees with upcoming birthdays, along with key details like name, designation, and contact information. Users can select an employee, draft a greeting message, and send emails directly from the interface. This helps streamline birthday and anniversary celebrations, promoting a positive work environment.",
   "tags": [
    "VBA",
    "Email",
    "HR tool"
   ],
   "image": "",
   "images": [],
   "link": ""
  },
  {
   "id": "layout",
   "title": "Production Floor Layout",
   "cat": "Excel",
   "summary": "A full factory floor plan drawn entirely in Excel.",
   "desc": "I've created this production floor layout using Excel, demonstrating that it's not just for calculations or data analysis. Excel can also be a powerful tool for drawing and designing to meet various needs. I enjoy experimenting and pushing the boundaries of what Excel can do, which is why I took on this project to try something different and creative",
   "tags": [
    "Excel drawing",
    "Layout"
   ],
   "image": "",
   "images": [],
   "link": ""
  },
  {
   "id": "opsportal",
   "title": "Operation Portal",
   "cat": "Web apps",
   "summary": "Internal web portal for day-to-day operations at Mainetti Bangladesh.",
   "desc": "Add a description of the Operation Portal: who uses it, what problems it solves and which modules it contains.",
   "tags": [
    "Web app",
    "Internal"
   ],
   "image": "",
   "images": [],
   "link": ""
  },
  {
   "id": "ciportal",
   "title": "CI Portal",
   "cat": "Web apps",
   "summary": "Continuous-improvement platform with Gemba Walk, KPI and Kaizen modules.",
   "desc": "Add a description of the CI Portal and its modules: Gemba Walk app and portal, KPI, Kaizen and more.",
   "tags": [
    "Gemba Walk",
    "KPI",
    "Kaizen"
   ],
   "image": "",
   "images": [],
   "link": ""
  },
  {
   "id": "gemba",
   "title": "Gemba Walk App",
   "cat": "Web apps",
   "summary": "Mobile companion for logging Gemba walk observations on the floor.",
   "desc": "Add a description of the Gemba Walk app and how it connects to the portal.",
   "tags": [
    "Mobile",
    "Gemba",
    "Lean"
   ],
   "image": "",
   "images": [],
   "link": ""
  },
  {
   "id": "android1",
   "title": "Android App 01",
   "cat": "Android",
   "summary": "Live on Google Play. Add app name, purpose and store link.",
   "desc": "Add the app description, download count and Play Store link.",
   "tags": [
    "Android",
    "Play Store"
   ],
   "image": "",
   "images": [],
   "link": ""
  },
  {
   "id": "android2",
   "title": "Android App 02",
   "cat": "Android",
   "summary": "Live on Google Play. Add app name, purpose and store link.",
   "desc": "Add the app description, download count and Play Store link.",
   "tags": [
    "Android",
    "Play Store"
   ],
   "image": "",
   "images": [],
   "link": ""
  }
 ],
 "portals": {
  "label": "02 — In-house platforms",
  "title": "Operations & CI",
  "italic": "portals.",
  "intro": "Web apps built for Mainetti Bangladesh to digitise shop-floor routines: Gemba walks, KPI tracking and Kaizen improvement ideas, feeding the same data model as the Power BI reports.",
  "cardTitle": "Operation Portal & CI Portal",
  "tag1": "Web app",
  "tag2": "Internal · Mainetti",
  "modulesLabel": "Modules",
  "image": ""
 },
 "modules": [
  {
   "name": "Gemba Walk",
   "kind": "App + portal"
  },
  {
   "name": "KPI",
   "kind": "Module"
  },
  {
   "name": "Kaizen",
   "kind": "Module"
  },
  {
   "name": "More modules",
   "kind": "In progress"
  }
 ],
 "shots": [
  {
   "label": "Gemba Walk · mobile app",
   "image": ""
  },
  {
   "label": "KPI module",
   "image": ""
  },
  {
   "label": "Kaizen module",
   "image": ""
  }
 ],
 "skillsHead": {
  "label": "02 — Skills",
  "title": "From raw ERP exports to",
  "italic": "decisions."
 },
 "skills": [
  {
   "name": "MS Excel",
   "area": "Analysis",
   "desc": "Expert in data analysis with power pivot, power query, data management with table relationships & advanced formulas",
   "tags": [
    "Power Pivot",
    "Power Query",
    "Advanced formulas"
   ]
  },
  {
   "name": "Power BI",
   "area": "BI",
   "desc": "Experienced in Power BI for creating various Dashboards, Data Cleaning, Transforming & Analysis of RAW data from different sources or systems.",
   "tags": [
    "Dashboards",
    "Data modeling",
    "ETL"
   ]
  },
  {
   "name": "Lean Six Sigma",
   "area": "Process",
   "desc": "Certified Yellow, Green and Black Belt. Root cause, Pareto and variance analysis applied to production and sales.",
   "tags": [
    "Kaizen",
    "Gemba",
    "RCA"
   ]
  },
  {
   "name": "Web & Android apps",
   "area": "Build",
   "desc": "Operations and CI web portals for Mainetti, plus Android apps published on Google Play.",
   "tags": [
    "Web apps",
    "Android",
    "Portals"
   ]
  }
 ],
 "badges": [
  {
   "value": "5%",
   "title": "LinkedIn Skill Assessment · MS Excel.",
   "text": "Top 5% of 30M people who took this test worldwide.",
   "tone": "accent"
  },
  {
   "value": "10%",
   "title": "Fiverr Skill Assessment · MS Excel.",
   "text": "Top 10% worldwide, 7.2/10 grade.",
   "tone": "blue"
  },
  {
   "value": "LSS",
   "title": "Lean Six Sigma certified.",
   "text": "Yellow, Green and Black Belt.",
   "tone": "accent"
  }
 ],
 "expHead": {
  "label": "04 — Experience",
  "title": "Where I've",
  "italic": "worked."
 },
 "jobs": [
  {
   "role": "Senior Data Analyst (Operation & Sales)",
   "company": "Mainetti Bangladesh Pvt. Ltd. (MNC)",
   "dates": "Nov 2021 — Present",
   "logo": "",
   "points": [
    "Act as the primary custodian of all sales and operational data, ensuring the highest standards of data accuracy and integrity through advanced validation and normalization methods.",
    "Track sales performance against targets and budgets, conduct variance and root cause analysis, and recommend actions to improve revenue, margin, and customer mix.",
    "Develop and maintain sophisticated BI dashboards and automated reports using Power BI, Power Pivot, and Power Query to track KPIs and enhance reporting effectiveness.",
    "Lead reporting automation and process improvement initiatives, acting as data custodian to strengthen analytics workflows, operational efficiency, and continuous improvement standards.",
    "Collaborate cross-functionally with Operation, Sales, Marketing, and IT teams to provide technical expertise in data modeling and support various analytical requirements.",
    "Support strategic planning and business reviews by analyzing service order backlogs and identifying root causes to optimize operational efficiency"
   ]
  },
  {
   "role": "Branch In-Charge (Operations & Sales)",
   "company": "Excel Telecom Pvt. Ltd. (Samsung Service, Naogaon)",
   "dates": "Feb 2021 — Oct 2021",
   "logo": "",
   "points": [
    "Analyze GSPN ERP server data for branch performance by order quantity & quality, spare parts consumptions, daily sales & deposit and customer feedback scores.",
    "Work on daily service order backlog data for pending service orders & identify actual reasons & actions to complete each order within due time.",
    "Submit day end operational, financial & performance reports correctly & perfectly to HQ within due time.",
    "Analyze spare parts consumption ERP data for keeping safety stock in the store & order new ones with minimum quantity for efficient & balanced business.",
    "Ensure KPI in excellent category & service is fully abide by management OPQC (Operational quality checklist) guidelines."
   ]
  },
  {
   "role": "Executive (Accounts & Store)",
   "company": "Fair Solutions Limited (Samsung Customer Service), Bogura",
   "dates": "Dec 2017 — Jan 2021",
   "logo": "",
   "points": [
    "Spare parts verification while receiving from Bangladesh Trade Syndicate Limited and supply it to the service engineers through GSPN server",
    "Analyze spare parts consumption data for keeping safety stock in the store & order new ones with minimum quantity for efficient & balanced business.",
    "Submit day end operational, financial & performance reports correctly & perfectly to HQ within due time.",
    "Monitoring daily income with cross checking through money receipt & GSPN server and deposit it to the bank. and maintain petty cash expense and verify employees conveyance receipt for register them."
   ]
  }
 ],
 "education": [
  {
   "period": "2022–2026",
   "degree": "B.Sc in Computer Engineering",
   "school": "City University · Final year"
  },
  {
   "period": "2010–2014",
   "degree": "Diploma in Engineering",
   "school": "City Polytechnic Institute · Garments Design & Pattern Making"
  }
 ],
 "contact": {
  "label": "06 — Contact",
  "head1": "Let's talk",
  "head2": "data",
  "email": "shuvo.ia@hotmail.com",
  "footer": "© 2026 Shuvo Ibn Alam",
  "location": "Ashulia, Savar, Dhaka"
 },
 "links": [
  {
   "label": "Email",
   "value": "shuvo.ia@hotmail.com",
   "href": "mailto:shuvo.ia@hotmail.com"
  },
  {
   "label": "LinkedIn",
   "value": "linkedin.com/in/shuvoo ↗",
   "href": "https://linkedin.com/in/shuvoo"
  },
  {
   "label": "Fiverr",
   "value": "fiverr.com/shuvoia ↗",
   "href": "https://fiverr.com/shuvoia"
  }
 ],
 "recsHead": {
  "label": "LinkedIn recommendations",
  "title": "What people",
  "italic": "say.",
  "linkedin": "https://www.linkedin.com/in/shuvoo/details/recommendations/"
 },
 "recommendations": [
  {
   "name": "Recommender name",
   "role": "Role · Company",
   "relation": "Managed Shuvo directly",
   "text": "Paste a LinkedIn recommendation here from the admin portal (Experience → Recommendations).",
   "photo": "",
   "link": ""
  },
  {
   "name": "Recommender name",
   "role": "Role · Company",
   "relation": "Worked with Shuvo",
   "text": "Paste a second recommendation here. Add, reorder or remove cards any time.",
   "photo": "",
   "link": ""
  }
 ],
 "site": {
  "gaId": ""
 }
});
