/* Visitor tracking & analytics for the portfolio.
   Site side: records page views and interactions (locally and, when configured, to Supabase).
   Admin side: getEvents() loads them, summarize() turns them into visits, visitors, trends and breakdowns. */
(function(window) {
  'use strict';
  if (window.__shuvoTrackerLoaded) return;   // never register listeners twice
  window.__shuvoTrackerLoaded = true;

  var STORAGE_KEY = 'shuvo_portfolio_analytics_v1';
  var VID_KEY = 'shuvo_portfolio_vid';
  var SESS_KEY = 'shuvo_portfolio_sess2';
  var OPT_KEY = 'shuvo_no_track';        // '1' = do not count visits from this browser
  var FORCE_KEY = 'shuvo_force_track';   // '1' = count even on localhost (for testing)
  var SESS_TIMEOUT_MS = 30 * 60 * 1000;  // 30 minutes of inactivity = a new visit
  var MAX_LOCAL = 1500;
  var DAY = 86400000;

  var SETUP_SQL = [
    '-- Visitor analytics for the portfolio. Run once in Supabase > SQL Editor > New query.',
    'create table if not exists public.site_activities (',
    '  id          bigint generated by default as identity primary key,',
    '  visitor_id  text,',
    '  session_id  text,',
    '  event_type  text not null,',
    '  detail      text,',
    '  page        text,',
    '  device      text,',
    '  browser     text,',
    '  os          text,',
    '  screen      text,',
    '  referrer    text,',
    '  timezone    text,',
    '  language    text,',
    '  created_at  timestamptz not null default now()',
    ');',
    'alter table public.site_activities add column if not exists session_id text;',
    'alter table public.site_activities add column if not exists language text;',
    'create index if not exists site_activities_created_idx on public.site_activities (created_at desc);',
    'create index if not exists site_activities_visitor_idx on public.site_activities (visitor_id);',
    'alter table public.site_activities enable row level security;',
    'drop policy if exists "anyone can insert activities" on public.site_activities;',
    'create policy "anyone can insert activities" on public.site_activities',
    '  for insert to anon, authenticated with check (true);',
    'drop policy if exists "admin can view activities" on public.site_activities;',
    'create policy "admin can view activities" on public.site_activities',
    '  for select to authenticated using (true);'
  ].join('\n');

  function rid(n) {
    var s = '';
    while (s.length < n) s += Math.random().toString(36).slice(2);
    return s.slice(0, n);
  }
  function p2(n) { return String(n).padStart(2, '0'); }
  function dayKey(ms) { var d = new Date(ms); return d.getFullYear() + '-' + p2(d.getMonth() + 1) + '-' + p2(d.getDate()); }
  function startOfDay(ms) { var d = new Date(ms); d.setHours(0, 0, 0, 0); return d.getTime(); }

  function cfg() {
    var c = window.PORTFOLIO_CONFIG || {};
    return { url: (c.supabaseUrl || '').replace(/\/$/, ''), anon: c.supabaseAnonKey || '' };
  }

  /* ---------- identity & session ---------- */

  function getVid() {
    try {
      var vid = localStorage.getItem(VID_KEY);
      if (!vid) { vid = 'v-' + rid(10); localStorage.setItem(VID_KEY, vid); }
      return vid;
    } catch (e) {
      if (!getVid.mem) getVid.mem = 'v-' + rid(10);
      return getVid.mem;
    }
  }

  // Session lives in localStorage so several tabs count as one visit.
  var memSess = null;
  function touchSession(now) {
    var s = null;
    try { s = JSON.parse(localStorage.getItem(SESS_KEY) || 'null'); } catch (e) {}
    if (!s) s = memSess;
    var isNew = false;
    if (!s || !s.id || now - s.last > SESS_TIMEOUT_MS) { s = { id: 's-' + rid(10), last: now }; isNew = true; }
    else s.last = now;
    memSess = s;
    try { localStorage.setItem(SESS_KEY, JSON.stringify(s)); } catch (e) {}
    return { id: s.id, isNew: isNew };
  }

  function shouldTrack() {
    try {
      if (localStorage.getItem(FORCE_KEY) !== '1') {
        var h = location.hostname;
        if (h === 'localhost' || h === '127.0.0.1' || h === '[::1]' || h === '::1' || /\.localhost$/.test(h)) return false;
      }
      if (navigator.webdriver) return false;
      if (/bot|crawl|spider|slurp|headless|lighthouse|pagespeed|facebookexternalhit|embedly|whatsapp|telegrambot|uptime|monitor/i.test(navigator.userAgent || '')) return false;
      if (localStorage.getItem(OPT_KEY) === '1') return false;
    } catch (e) {}
    return true;
  }

  function getClientMeta() {
    var ua = navigator.userAgent || '';
    var browser = 'Other';
    if (/Edg\//i.test(ua)) browser = 'Edge';
    else if (/OPR\/|Opera/i.test(ua)) browser = 'Opera';
    else if (/SamsungBrowser/i.test(ua)) browser = 'Samsung';
    else if (/Firefox\//i.test(ua)) browser = 'Firefox';
    else if (/Chrome\//i.test(ua) || /CriOS/i.test(ua)) browser = 'Chrome';
    else if (/Safari\//i.test(ua)) browser = 'Safari';

    var os = 'Other';
    if (/Windows/i.test(ua)) os = 'Windows';
    else if (/Android/i.test(ua)) os = 'Android';
    else if (/iPhone|iPad|iPod/i.test(ua)) os = 'iOS';
    else if (/Macintosh|Mac OS X/i.test(ua)) os = (navigator.maxTouchPoints > 1) ? 'iOS' : 'macOS';
    else if (/CrOS/i.test(ua)) os = 'ChromeOS';
    else if (/Linux/i.test(ua)) os = 'Linux';

    var device = 'Desktop';
    if (/iPad|Tablet/i.test(ua) || (/Macintosh/i.test(ua) && navigator.maxTouchPoints > 1)) device = 'Tablet';
    else if (/Mobile|Android|iPhone|iPod/i.test(ua)) device = 'Mobile';
    else if (window.innerWidth < 768) device = 'Mobile';

    var ref = 'Direct';
    try {
      var q = new URLSearchParams(location.search);
      var u = q.get('utm_source') || q.get('ref') || q.get('source');
      if (u) ref = String(u).slice(0, 40);
    } catch (e) {}
    if (ref === 'Direct' && document.referrer) {
      try {
        var rUrl = new URL(document.referrer);
        if (rUrl.hostname !== location.hostname) ref = rUrl.hostname.replace(/^www\./, '');
      } catch (e) { ref = document.referrer.slice(0, 32); }
    }

    var screenRes = (window.screen && window.screen.width) ? (window.screen.width + 'x' + window.screen.height) : 'Unknown';
    var tz = 'Unknown';
    try { tz = Intl.DateTimeFormat().resolvedOptions().timeZone || 'Unknown'; } catch (e) {}
    var lang = (navigator.language || '').slice(0, 12);

    return { browser: browser, os: os, device: device, referrer: ref, screenRes: screenRes, tz: tz, lang: lang };
  }

  /* ---------- local store (this browser only) ---------- */

  function getLocalActivities() {
    try {
      var parsed = JSON.parse(localStorage.getItem(STORAGE_KEY) || 'null');
      if (parsed && Array.isArray(parsed.activities)) return parsed.activities;
    } catch (e) {}
    return [];
  }
  function saveLocalActivities(list) {
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify({ v: 2, activities: list.slice(0, MAX_LOCAL) }));
      window.dispatchEvent(new CustomEvent('portfolio-analytics-update'));
    } catch (e) {}
  }

  /* ---------- sending ---------- */

  function postRow(c, body) {
    return fetch(c.url + '/rest/v1/site_activities', {
      method: 'POST',
      headers: { 'apikey': c.anon, 'Authorization': 'Bearer ' + c.anon, 'Content-Type': 'application/json', 'Prefer': 'return=minimal' },
      body: JSON.stringify(body),
      keepalive: true
    });
  }

  // Returns a promise of { ok, status, text } so callers can report problems.
  function syncToSupabase(payload) {
    var c = cfg();
    if (!c.url || !c.anon) return Promise.resolve({ ok: false, status: 0, text: 'not configured' });
    return postRow(c, payload).then(function(r) {
      if (r.ok) return { ok: true, status: r.status, text: '' };
      return r.text().then(function(t) {
        // Older tables lack the newer columns: retry without them rather than lose the visit.
        if (r.status === 400 && /PGRST204|column/i.test(t)) {
          var slim = {};
          Object.keys(payload).forEach(function(k) { if (k !== 'session_id' && k !== 'language') slim[k] = payload[k]; });
          return postRow(c, slim).then(function(r2) { return { ok: r2.ok, status: r2.status, text: '' }; });
        }
        return { ok: false, status: r.status, text: t };
      });
    }).catch(function(e) { return { ok: false, status: 0, text: String(e && e.message || e) }; });
  }

  var activeMs = 0, lastTick = document.hidden ? 0 : Date.now(), lastSent = 0, started = false;

  function recordActivity(type, detail, meta) {
    meta = meta || {};
    if (!shouldTrack()) return null;
    var now = Date.now();
    var sess = touchSession(now);
    var vid = getVid();
    var client = getClientMeta();
    var pageName = meta.page || (location.pathname || '/').replace(/^\/+|\/+$/g, '') || (location.hash ? location.hash.replace(/^#/, '') : 'intro') || 'intro';
    if (type === 'page_view') {
      started = true;
      var lp = recordActivity.lastPV;   // ignore an identical page view repeated within 3 seconds
      if (lp && lp.page === pageName && now - lp.time < 3000) return null;
      recordActivity.lastPV = { page: pageName, time: now };
    }

    var item = {
      id: 'act_' + now + '_' + rid(4),
      time: now, vid: vid, sid: sess.id, type: type, detail: detail || '', page: pageName,
      device: client.device, browser: client.browser, os: client.os, screen: client.screenRes,
      referrer: client.referrer, tz: client.tz, lang: client.lang
    };
    var list = getLocalActivities();
    list.unshift(item);
    saveLocalActivities(list);

    syncToSupabase({
      visitor_id: vid, session_id: sess.id, event_type: type, detail: detail || '', page: pageName,
      device: client.device, browser: client.browser, os: client.os, screen: client.screenRes,
      referrer: client.referrer, timezone: client.tz, language: client.lang
    });
    return item;
  }

  // Time on site: counts only the time the tab is visible, reported when the visitor leaves or switches tab.
  function sendTime() {
    if (lastTick) { activeMs += Date.now() - lastTick; lastTick = 0; }
    var s = Math.round(activeMs / 1000);
    if (started && s >= 3 && s !== lastSent) { lastSent = s; recordActivity('time_on_site', String(s)); }
  }
  try {
    document.addEventListener('visibilitychange', function() {
      if (document.hidden) sendTime(); else lastTick = Date.now();
    });
    window.addEventListener('pagehide', sendTime);
  } catch (e) {}

  /* ---------- reading (admin) ---------- */

  var BASE_COLS = 'id,visitor_id,event_type,detail,page,device,browser,os,screen,referrer,timezone,created_at';
  var FULL_COLS = BASE_COLS + ',session_id,language';

  function fetchAll(c, token, cols) {
    var out = [], page = 0, PAGE = 1000, MAX = 10;
    function next() {
      return fetch(c.url + '/rest/v1/site_activities?select=' + cols + '&order=created_at.desc&limit=' + PAGE + '&offset=' + (page * PAGE), {
        headers: { 'apikey': c.anon, 'Authorization': 'Bearer ' + token }
      }).then(function(r) {
        if (!r.ok) return r.text().then(function(t) { var e = new Error(t || ('HTTP ' + r.status)); e.status = r.status; e.body = t; throw e; });
        return r.json();
      }).then(function(rows) {
        out = out.concat(rows); page++;
        if (rows.length === PAGE && page < MAX) return next();
        return { rows: out, truncated: rows.length === PAGE && page >= MAX };
      });
    }
    return next();
  }

  function rowToEvent(r) {
    return {
      id: 'sb_' + r.id, time: r.created_at ? Date.parse(r.created_at) : Date.now(), vid: r.visitor_id || 'unknown',
      sid: r.session_id || '', type: r.event_type, detail: r.detail || '', page: r.page || 'intro',
      device: r.device || 'Desktop', browser: r.browser || 'Other', os: r.os || 'Other', screen: r.screen || '',
      referrer: r.referrer || 'Direct', tz: r.timezone || '', lang: r.language || ''
    };
  }

  // Resolves { events, isRemote, configured, error, errorText, truncated }. Never rejects.
  function getEvents(token) {
    var c = cfg();
    var configured = !!(c.url && c.anon);
    var local = function() { return getLocalActivities(); };
    if (configured && token) {
      return fetchAll(c, token, FULL_COLS).catch(function(e) {
        if (e.status === 400) return fetchAll(c, token, BASE_COLS);   // older table without the newer columns
        throw e;
      }).then(function(res) {
        return { events: res.rows.map(rowToEvent), isRemote: true, configured: true, error: null, errorText: '', truncated: res.truncated };
      }).catch(function(e) {
        var body = e && e.body || '';
        var kind = (e && e.status === 404) || /PGRST205|PGRST106|does not exist/i.test(body) ? 'missing_table'
          : (e && (e.status === 401 || e.status === 403)) ? 'denied' : 'error';
        return { events: local(), isRemote: false, configured: true, error: kind, errorText: String(body || (e && e.message) || '').slice(0, 200), truncated: false };
      });
    }
    return Promise.resolve({ events: local(), isRemote: false, configured: configured, error: configured ? 'signed_out' : null, errorText: '', truncated: false });
  }

  /* ---------- analysis ---------- */

  var TZ_COUNTRY = {
    'Asia/Dhaka': 'Bangladesh', 'Asia/Kolkata': 'India', 'Asia/Calcutta': 'India', 'Asia/Karachi': 'Pakistan', 'Asia/Colombo': 'Sri Lanka',
    'Asia/Kathmandu': 'Nepal', 'Asia/Dubai': 'UAE', 'Asia/Riyadh': 'Saudi Arabia', 'Asia/Qatar': 'Qatar', 'Asia/Kuwait': 'Kuwait',
    'Asia/Singapore': 'Singapore', 'Asia/Kuala_Lumpur': 'Malaysia', 'Asia/Bangkok': 'Thailand', 'Asia/Jakarta': 'Indonesia',
    'Asia/Manila': 'Philippines', 'Asia/Ho_Chi_Minh': 'Vietnam', 'Asia/Hong_Kong': 'Hong Kong', 'Asia/Shanghai': 'China',
    'Asia/Tokyo': 'Japan', 'Asia/Seoul': 'South Korea', 'Asia/Tehran': 'Iran', 'Asia/Jerusalem': 'Israel', 'Asia/Baghdad': 'Iraq',
    'Europe/London': 'United Kingdom', 'Europe/Dublin': 'Ireland', 'Europe/Paris': 'France', 'Europe/Berlin': 'Germany',
    'Europe/Madrid': 'Spain', 'Europe/Rome': 'Italy', 'Europe/Amsterdam': 'Netherlands', 'Europe/Brussels': 'Belgium',
    'Europe/Zurich': 'Switzerland', 'Europe/Vienna': 'Austria', 'Europe/Stockholm': 'Sweden', 'Europe/Oslo': 'Norway',
    'Europe/Copenhagen': 'Denmark', 'Europe/Helsinki': 'Finland', 'Europe/Warsaw': 'Poland', 'Europe/Istanbul': 'Turkey',
    'Europe/Moscow': 'Russia', 'Europe/Kiev': 'Ukraine', 'Europe/Kyiv': 'Ukraine', 'Europe/Lisbon': 'Portugal', 'Europe/Athens': 'Greece',
    'America/New_York': 'United States', 'America/Chicago': 'United States', 'America/Denver': 'United States',
    'America/Los_Angeles': 'United States', 'America/Phoenix': 'United States', 'America/Anchorage': 'United States',
    'America/Toronto': 'Canada', 'America/Vancouver': 'Canada', 'America/Mexico_City': 'Mexico', 'America/Sao_Paulo': 'Brazil',
    'America/Argentina/Buenos_Aires': 'Argentina', 'America/Bogota': 'Colombia', 'America/Lima': 'Peru', 'America/Santiago': 'Chile',
    'Africa/Cairo': 'Egypt', 'Africa/Lagos': 'Nigeria', 'Africa/Nairobi': 'Kenya', 'Africa/Johannesburg': 'South Africa',
    'Africa/Casablanca': 'Morocco', 'Africa/Accra': 'Ghana', 'Africa/Addis_Ababa': 'Ethiopia',
    'Australia/Sydney': 'Australia', 'Australia/Melbourne': 'Australia', 'Australia/Perth': 'Australia', 'Australia/Brisbane': 'Australia',
    'Pacific/Auckland': 'New Zealand', 'UTC': 'Unknown', 'Etc/UTC': 'Unknown'
  };
  function countryOf(tz) {
    if (!tz || tz === 'Unknown') return 'Unknown';
    return TZ_COUNTRY[tz] || tz.split('/').pop().replace(/_/g, ' ');
  }
  function sourceOf(ref) {
    ref = String(ref || 'Direct');
    if (ref === 'Direct') return 'Direct';
    var r = ref.toLowerCase();
    if (/linkedin|lnkd\.in/.test(r)) return 'LinkedIn';
    if (/google/.test(r)) return 'Google';
    if (/bing/.test(r)) return 'Bing';
    if (/duckduckgo/.test(r)) return 'DuckDuckGo';
    if (/facebook|fb\.com|fb\.me/.test(r)) return 'Facebook';
    if (/(^|\.)t\.co$|twitter|(^|\.)x\.com$/.test(r)) return 'X (Twitter)';
    if (/fiverr/.test(r)) return 'Fiverr';
    if (/whatsapp|wa\.me/.test(r)) return 'WhatsApp';
    if (/github/.test(r)) return 'GitHub';
    if (/youtube|youtu\.be/.test(r)) return 'YouTube';
    if (/instagram/.test(r)) return 'Instagram';
    if (/reddit/.test(r)) return 'Reddit';
    if (/mail\.|outlook|gmail/.test(r)) return 'Email';
    return ref;
  }

  function buildSessions(evsAsc) {
    var map = {}, lastByVid = {}, counters = {}, list = [];
    evsAsc.forEach(function(e) {
      var key;
      if (e.sid) key = 's:' + e.sid;
      else {
        var l = lastByVid[e.vid];
        if (l === undefined || e.time - l > SESS_TIMEOUT_MS) counters[e.vid] = (counters[e.vid] || 0) + 1;
        lastByVid[e.vid] = e.time;
        key = 'v:' + e.vid + ':' + counters[e.vid];
      }
      var s = map[key];
      if (!s) {
        s = map[key] = { id: key, vid: e.vid, start: e.time, end: e.time, pv: 0, act: 0, secs: 0,
          device: e.device, browser: e.browser, os: e.os, ref: e.referrer, tz: e.tz, lang: e.lang, screen: e.screen };
        list.push(s);
      }
      if (e.time > s.end) s.end = e.time;
      if (e.type === 'time_on_site') { var n = parseInt(e.detail, 10); if (n > s.secs) s.secs = n; }
      else if (e.type === 'page_view') s.pv++;
      else if (e.type !== 'theme_toggle') s.act++;
    });
    return list;
  }
  function durOf(s) { return Math.max(s.secs, (s.end - s.start) / 1000); }

  function kpis(sessions, evs, startMs, endMs, firstSeen) {
    var inS = sessions.filter(function(s) { return s.start >= startMs && s.start < endMs; });
    var vis = {};
    inS.forEach(function(s) { vis[s.vid] = (vis[s.vid] || 0) + 1; });
    var ids = Object.keys(vis);
    var returning = ids.filter(function(v) { return vis[v] > 1 || firstSeen[v] < startMs; }).length;
    var pv = 0;
    evs.forEach(function(e) { if (e.type === 'page_view' && e.time >= startMs && e.time < endMs) pv++; });
    var durs = inS.map(durOf).filter(function(x) { return x > 0; });
    var avg = durs.length ? durs.reduce(function(a, b) { return a + b; }, 0) / durs.length : 0;
    var bounces = inS.filter(function(s) { return s.pv <= 1 && s.act === 0 && durOf(s) < 15; }).length;
    return {
      visits: inS.length, visitors: ids.length, pageViews: pv, avgSecs: avg,
      bounceRate: inS.length ? bounces / inS.length * 100 : 0,
      returningRate: ids.length ? returning / ids.length * 100 : 0,
      pagesPerVisit: inS.length ? pv / inS.length : 0
    };
  }

  function tally(map, key) { map[key] = (map[key] || 0) + 1; }
  function toList(map, limit) {
    var arr = Object.keys(map).map(function(k) { return { name: k, count: map[k] }; }).sort(function(a, b) { return b.count - a.count; });
    return limit ? arr.slice(0, limit) : arr;
  }

  // days: 1 = today, 7, 30, or 0 = all time.
  function summarize(events, opts) {
    opts = opts || {};
    var days = opts.days === undefined ? 30 : opts.days;
    var now = Date.now();
    var evs = (events || []).filter(function(e) { return e && e.type !== 'test'; }).slice().sort(function(a, b) { return a.time - b.time; });
    var sessions = buildSessions(evs);

    var firstSeen = {};
    sessions.forEach(function(s) { if (firstSeen[s.vid] === undefined || s.start < firstSeen[s.vid]) firstSeen[s.vid] = s.start; });

    var todayStart = startOfDay(now);
    var start = days === 0 ? 0 : (days === 1 ? todayStart : todayStart - (days - 1) * DAY);
    var end = now + 1;
    var cur = kpis(sessions, evs, start, end, firstSeen);
    var prev = null;
    if (days > 0) {
      var span = end - start;
      prev = kpis(sessions, evs, start - span, start, firstSeen);
    }

    var inS = sessions.filter(function(s) { return s.start >= start && s.start < end; });
    var inE = evs.filter(function(e) { return e.time >= start && e.time < end; });

    // Trend buckets
    var series = [], keyFn;
    if (days === 1) {
      for (var h = 0; h < 24; h++) series.push({ key: h, label: p2(h) + ':00', visits: 0, vset: {} });
      keyFn = function(s) { return new Date(s.start).getHours(); };
    } else {
      var n = days === 0 ? 0 : days;
      if (days === 0) {
        var first = sessions.length ? startOfDay(sessions[0].start) : todayStart;
        n = Math.min(90, Math.round((todayStart - first) / DAY) + 1);
      }
      var mon = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
      for (var i = n - 1; i >= 0; i--) {
        var d = new Date(todayStart - i * DAY);
        series.push({ key: dayKey(d.getTime()), label: mon[d.getMonth()] + ' ' + d.getDate(), visits: 0, vset: {} });
      }
      keyFn = function(s) { return dayKey(s.start); };
    }
    var byKey = {};
    series.forEach(function(b) { byKey[b.key] = b; });
    inS.forEach(function(s) { var b = byKey[keyFn(s)]; if (b) { b.visits++; b.vset[s.vid] = 1; } });
    series = series.map(function(b) { return { key: b.key, label: b.label, visits: b.visits, visitors: Object.keys(b.vset).length }; });

    // Busiest hours (visitor's browser time shown in the admin's time zone)
    var hours = []; for (var hh = 0; hh < 24; hh++) hours.push(0);
    inS.forEach(function(s) { hours[new Date(s.start).getHours()]++; });

    // Event breakdowns
    var pages = {}, projects = {}, contacts = {};
    var act = { cv: 0, contact: 0, cta: 0, form: 0, certs: 0, photos: 0, demos: 0, recs: 0, projectViews: 0 };
    inE.forEach(function(e) {
      if (e.type === 'page_view') tally(pages, e.page || 'intro');
      else if (e.type === 'project_view') { act.projectViews++; tally(projects, (e.detail || '').replace(/^Explored project:\s*/i, '') || 'Project'); }
      else if (e.type === 'cv_download' || e.type === 'cv_click') act.cv++;
      else if (e.type === 'contact_click') { act.contact++; tally(contacts, (e.detail || '').replace(/^Clicked contact:\s*/i, '') || 'Contact'); }
      else if (e.type === 'cta_click') { act.cta++; tally(contacts, e.detail || 'Call to action'); }
      else if (e.type === 'contact_form') act.form++;
      else if (e.type === 'cert_view') act.certs++;
      else if (e.type === 'photo_view') act.photos++;
      else if (e.type === 'dashboard_open') act.demos++;
      else if (e.type === 'recommendation_view') act.recs++;
    });

    // Audience breakdowns (by visit)
    var devices = {}, browsers = {}, os = {}, sources = {}, countries = {}, langs = {}, screens = {};
    inS.forEach(function(s) {
      tally(devices, s.device || 'Desktop'); tally(browsers, s.browser || 'Other'); tally(os, s.os || 'Other');
      tally(sources, sourceOf(s.ref)); tally(countries, countryOf(s.tz));
      if (s.lang) tally(langs, s.lang.toLowerCase());
      if (s.screen && s.screen !== 'Unknown') tally(screens, s.screen);
    });

    // Live feed (newest first; background timing events are hidden)
    var feed = evs.filter(function(e) { return e.type !== 'time_on_site'; }).slice(-150).reverse();

    var fiveMin = {};
    evs.forEach(function(e) { if (now - e.time < 5 * 60000) fiveMin[e.vid] = 1; });

    var allV = {}; sessions.forEach(function(s) { allV[s.vid] = 1; });

    return {
      days: days, kpis: cur, prev: prev, series: series, hours: hours,
      pages: toList(pages), projects: toList(projects, 8), contacts: toList(contacts, 6), actions: act,
      devices: toList(devices), browsers: toList(browsers), os: toList(os), sources: toList(sources, 8),
      countries: toList(countries, 8), languages: toList(langs, 6), screens: toList(screens, 6),
      feed: feed, online: Object.keys(fiveMin).length,
      today: kpis(sessions, evs, todayStart, end, firstSeen),
      allTime: { visits: sessions.length, visitors: Object.keys(allV).length, events: evs.length },
      firstEvent: evs.length ? evs[0].time : 0, lastEvent: evs.length ? evs[evs.length - 1].time : 0,
      hasData: evs.length > 0
    };
  }

  /* ---------- testing helpers ---------- */

  function sendTestEvent() {
    var c = cfg();
    return syncToSupabase({
      visitor_id: 'admin-check', session_id: 'admin-check', event_type: 'test', detail: 'Admin connectivity check',
      page: 'admin', device: 'Desktop', browser: 'Admin', os: 'Admin', screen: '', referrer: 'Direct', timezone: '', language: ''
    });
  }

  function recordTestVisit() {
    var b = ['Chrome', 'Safari', 'Edge', 'Firefox'], o = ['Windows', 'macOS', 'iOS', 'Android'];
    var pages = ['intro', 'projects', 'skills', 'certifications', 'experience', 'recommendations', 'reviews', 'hobbies', 'contact'];
    var tzs = ['Asia/Dhaka', 'Asia/Kolkata', 'Europe/London', 'America/New_York', 'Asia/Dubai', 'Asia/Singapore'];
    var refs = ['Direct', 'linkedin.com', 'google.com', 'fiverr.com'];
    var pick = function(a) { return a[Math.floor(Math.random() * a.length)]; };
    var os = pick(o), device = (os === 'iOS' || os === 'Android') ? 'Mobile' : pick(['Desktop', 'Desktop', 'Tablet']);
    var vid = 'v-' + rid(8), sid = 's-' + rid(8), ref = pick(refs), tz = pick(tzs), br = pick(b), now = Date.now();
    var mk = function(i, type, detail, page) {
      return { id: 'test_' + now + '_' + i, time: now - (3 - i) * 20000, vid: vid, sid: sid, type: type, detail: detail, page: page,
        device: device, browser: br, os: os, screen: device === 'Mobile' ? '390x844' : '1920x1080', referrer: ref, tz: tz, lang: 'en-US' };
    };
    var p1 = pick(pages), p2_ = pick(pages);
    var evs = [mk(0, 'page_view', 'Viewed ' + p1, p1), mk(1, 'page_view', 'Viewed ' + p2_, p2_), mk(2, 'project_view', 'Explored project: Sample Dashboard', 'projects'), mk(3, 'time_on_site', String(40 + Math.floor(Math.random() * 90)), p2_)];
    var list = getLocalActivities();
    evs.forEach(function(e) { list.unshift(e); });
    saveLocalActivities(list);
    return evs[0];
  }

  function clearData() {
    try {
      localStorage.removeItem(STORAGE_KEY);
      localStorage.removeItem(SESS_KEY);
      memSess = null;
      window.dispatchEvent(new CustomEvent('portfolio-analytics-update'));
    } catch (e) {}
  }

  window.PortfolioTracker = {
    trackVisit: function(page) { return recordActivity('page_view', 'Viewed ' + (page || 'Intro'), { page: page }); },
    trackPage: function(page) { return recordActivity('page_view', 'Viewed ' + (page || 'Intro'), { page: page }); },
    trackEvent: function(type, detail, meta) { return recordActivity(type, detail, meta); },
    getEvents: getEvents,
    summarize: summarize,
    sendTestEvent: sendTestEvent,
    recordTestVisit: recordTestVisit,
    clearData: clearData,
    countryOf: countryOf,
    setupSql: SETUP_SQL,
    isCounting: function() { try { return localStorage.getItem(OPT_KEY) !== '1'; } catch (e) { return true; } },
    setCounting: function(on) { try { localStorage.setItem(OPT_KEY, on ? '0' : '1'); } catch (e) {} },
    optOutUnset: function() { try { return localStorage.getItem(OPT_KEY) === null; } catch (e) { return false; } }
  };

})(window);
